### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by tfmorris** [human-pangenomics/hpp_production_workflows#14]
There's currently no license associated with the code in this repo, making it impossible to reuse. Please consider adding a permissive license.

**Comment by juklucas** [comment]
Thank you both. Totally agreed.

I have added two commits to [update the README](https://github.com/human-pangenomics/hpp_production_workflows/commit/03c918ae134b115ba57d63e21ea3e14ddac2528a) and [add the MIT License](https://github.com/human-pangenomics/hpp_production_workflows/commit/af680dd53bdace6b21de21c69992a195dcf45b9b).

I was a bit careful with my language (see below for what I put in the REAMDE) as I don't currently know the state of the licenses for all of the tools that we write WDLs/containers for. Please let me know if this is not sufficient. 

> All WDLs and containers created in this repository are licensed under the MIT license. The underlying tools (that the WDLs and containers run) are likely covered under one or more Free and Open Source Software licenses, but we cannot make any guarantees to that fact.

**Comment by junaruga** [comment]
> I was a bit careful with my language (see below for what I put in the REAMDE) as I don't currently know the state of the licenses for all of the tools that we write WDLs/containers for. Please let me know if this is not sufficient.

Thanks for the work! I think the MIT license is a great choice as a permissive license. And as potentially the licenses of the tools that executed in containers can be changed any time. So, the updated text about the license looks good.
