### ISSUE TITLE
Is the "Ensembl Mapping Pipeline for Assembly Annotation" source codes available ?

### ISSUE THREAD

**Issue by PengJia6** [human-pangenomics/hpp_production_workflows#17]
Hi all,

I want to use the **Ensembl Mapping Pipeline** in HPRC paper ([A Draft Human Pangenome Reference](https://www.biorxiv.org/content/10.1101/2022.07.09.499321v1)) to evaluate my assemblies, but I could not find the source codes in this repository.  Is this pipeline not publicly available? Or am I missing something? 

BTW, the pipeline is descriped at page 46 of the HPRC [manuscript](https://www.biorxiv.org/content/10.1101/2022.07.09.499321v1.full.pdf) and Supplementary Figure 46.

Thanks!

Best,
Peng

**Comment by juklucas** [comment]
Thank you both for writing in. This analysis was done by Ensembl so the code is not housed in this repo. I'll reach out to the Ensembl team to see if they have something that they can publicly point to (like a GitHub repo) for their gene annotation that they did for the HPRC.

**Comment by juklucas** [comment]
I heard back from Ensembl and the code can be found [here](https://github.com/Ensembl/ensembl-analysis/tree/experimental/humanpangenome_v1.2.2) and the config for creating the pipeline in eHive is [here](https://github.com/Ensembl/ensembl-analysis/blob/experimental/humanpangenome_v1.2.2/modules/Bio/EnsEMBL/Analysis/Hive/Config/Human_anno_conf.pm). I'm told that this code is heavily linked to Ensembl's infrastructure, and this branch of the code is still very much in development.

As an alternative, LiftOff offers a somewhat similar approach to mapping the genes, but is much easier to get working in your own environment.

If you have specific questions about the pipeline, Ensembl is happy to help. You can reach them at: helpdesk@ensembl.org
