### ISSUE TITLE
clarify data source for HSat annotation

### ISSUE THREAD

**Issue by ptrebert** [human-pangenomics/hpp_production_workflows#7]
Hi,
could you please clarify the data source for the chm13v1.1/HSat annotation used in this step:
```
2. Incorporating HSATs Coverage Bias
[...]
To do so we need a bed file pointing to the HSat in the reference then we can run the script project_blocks.py to project it back to the assembly.
```
Or is that already packaged in the container? Thanks!
+Peter

**Comment by mobinasri** [comment]
@ptrebert Sorry for the delay. I missed this issue.
You can find the bed files pointing to the HSat coverage-biased blocks here:
https://github.com/mobinasri/flagger/tree/main/misc/biased_regions
They are in the CHM13-v1.1 coordinates.
